from gensim.models import Doc2Vec
from sklearn.cluster import DBSCAN
import numpy as np
import matplotlib.pyplot as plt

d2v_film_model = Doc2Vec.load('doc2vec_data_film.model')

string1 = "the mummy 1999 american action horror film 2 written directed stephen sommers it loose remake 1932 film name stars brendan fraser rachel weisz john hannah kevin j o connor arnold vosloo titular role reanimated mummy 3 the film follows adventurer rick o connell travels hamunaptra city dead librarian brother accidentally awaken imhotep cursed high priest reign pharaoh seti i filming began marrakech morocco may 4 1998 lasted seventeen weeks the crew endured dehydration sandstorms snakes work sahara desert the film first use natural crater formation gara medouar later used bond movie spectre 2015 others industrial light magic provided visual effects blended film computer generated imagery create mummy jerry goldsmith provided orchestral score the mummy opened may 7 1999 grossed 43 million 3 210 theaters opening weekend united states the film went gross 416 million worldwide the box office success led two sequels the mummy returns 2001 the mummy tomb dragon emperor 2008 as well animated series prequel spin off film the scorpion king 2002 "
string2= "pirates caribbean the curse black pearl 2003 american fantasy swashbuckler film directed gore verbinski first film pirates caribbean film series produced walt disney pictures jerry bruckheimer film based walt disney s pirates caribbean attraction disney theme parks 3 the story follows pirate jack sparrow johnny depp blacksmith will turner orlando bloom rescue kidnapped elizabeth swann keira knightley cursed crew black pearl captained hector barbossa geoffrey rush become undead skeletons night jay wolpert developed script 2001 stuart beattie rewrote early 2002 around time producer jerry bruckheimer became involved project ted elliott terry rossio work script adding plot device supernatural curse story bring line original theme park ride filming took place october 2002 march 2003 saint vincent grenadines sets constructed around los angeles california it also significant first film released walt disney pictures banner rated pg 13 mpaa the film s world premiere held disneyland park anaheim california june 28 2003 despite low expectations film huge box office success grossed 654 3 million worldwide making fourth highest grossing film 2003 it received generally positive reviews critics film praised performances particularly depp action sequences writing score visuals the film widely seen film launched depp box office leading man many years cult movie star depp screen actors guild award outstanding performance male actor leading role addition best actor nominations academy awards baftas golden globes the curse black pearl also nominated four academy awards baftas the film became first franchise two back to back sequels dead man s chest at world s end released 2006 2007 two sequels on stranger tides dead men tell no tales released 2011 2017 respectively "
string3 = "the mummy 1999 american action horror film 2 written directed stephen sommers it loose remake 1932 film name stars brendan fraser rachel weisz john hannah kevin j o connor arnold vosloo titular role reanimated mummy 3 the film follows adventurer rick o connell travels hamunaptra city dead librarian brother accidentally awaken imhotep cursed high priest reign pharaoh seti i filming began marrakech morocco may 4 1998 lasted seventeen weeks the crew endured dehydration sandstorms snakes work sahara desert the film first use natural crater formation gara medouar later used bond movie spectre 2015 others industrial light magic provided visual effects blended film computer generated imagery create mummy jerry goldsmith provided orchestral score the mummy opened may 7 1999 grossed 43 million 3 210 theaters opening weekend united states the film went gross 416 million worldwide the box office success led two sequels the mummy returns 2001 the mummy tomb dragon emperor 2008 as well animated series prequel spin off film the scorpion king 2002 "
string4 = "pirates caribbean dead men tell tales released countries pirates caribbean salazar revenge 2017 american swashbuckler fantasy film fifth installment pirates caribbean film series sequel stranger tides 2011 film directed joachim rønning espen sandberg script jeff nathanson jerry bruckheimer serving producer johnny depp kevin mcnally geoffrey rush reprise roles jack sparrow joshamee gibbs hector barbossa respectively joined cast javier bardem brenton thwaites kaya scodelario film captain jack sparrow searches trident poseidon pursued undead sea captain crew filmmakers cited series first installment curse black pearl 2003 inspiration script tone film pre production film started shortly stranger tides released early 2011 terry rossio writing initial script early 2013 jeff nathanson hired write new script film depp involved nathanson writing process initially planned 2015 release film delayed 2016 2017 6 years development hell due script budget issues principal photography started australia february 2015 australian government offered disney 20 million tax incentives ended july 2015 dead men tell tales released united states conventional 3d imax formats may 26 2017 film received generally mixed reviews critics praising visual effects performances cast film sense fun criticizing story direction 6 7 grossed 794 million worldwide production budget 230 320 million making one highest grossing films 2017 lowest total series since curse black pearl"
string5 = "clueless 1995 american coming age romantic comedy film written directed amy heckerling stars alicia silverstone stacey dash paul rudd dan hedaya brittany murphy clueless produced scott rudin robert lawrence loosely based jane austen 1815 novel emma modern day setting beverly hills plot centers cher horowitz high school student befriends new student named tai frasier decides give makeover clueless filmed california 40 day schedule film director heckerling studied real beverly hills high school students learn lingo understand real teens 1990s talked film grossed 56 1 million united states received generally positive reviews critics considered one best teen films time clueless developed cult following continuing legacy film followed spin television sitcom series books paramount studios announced producing remake "
string6 = "indiana jones temple doom 1984 american action adventure film directed steven spielberg second installment indiana jones franchise prequel 1981 film raiders lost ark featuring harrison ford reprising role title character arriving north india indiana jones asked desperate villagers find mystical stone rescue children thuggee cult practicing child slavery black magic ritualistic human sacrifice honor goddess kali executive producer co writer george lucas made film prequel want nazis villains three rejected plot devices lucas wrote film treatment resembled film final storyline lawrence kasdan lucas collaborator raiders lost ark turned offer write script willard huyck gloria katz hired replacements screenplay partly based upon 1939 film gunga din film released financial success initial reviews mixed criticizing dark tone however critical opinion improved since 1984 citing film intensity imagination response violent sequences film similar complaints gremlins spielberg suggested motion picture association america mpaa alter rating system within two months film release creating new pg 13 rating released may 23 1984 film followed indiana jones last crusade 1989"
string7 = "pride prejudice 2005 romance film directed joe wright based jane austen s 1813 novel name the film depicts five sisters english family landed gentry deal issues marriage morality misconceptions keira knightley stars lead role elizabeth bennet matthew macfadyen plays romantic interest mr darcy produced working title films association studiocanal film released 16 september 2005 united kingdom ireland 11 november united states screenwriter deborah moggach initially attempted make script faithful novel possible writing elizabeth s perspective preserving much original dialogue wright directing first feature film encouraged greater deviation text including changing dynamics within bennet family wright moggach set film earlier period avoided depicting perfectly clean regency world presenting instead muddy hem version time it shot entirely location england 15 week schedule wright found casting difficult due past performances particular characters the filmmakers balance thought best role studio s desire stars knightley well known part work pirates caribbean film series macfadyen international name recognition the film s themes emphasise realism romanticism family it marketed younger mainstream audience promotional items noted came producers 2001 s romantic comedy bridget jones s diary acknowledging provenance austen novel pride prejudice earned worldwide gross approximately 121 million considered commercial success pride prejudice earned rating 82 review aggregator metacritic labeling universally acclaimed it earned four nominations 78th academy awards including best actress nomination knightley austen scholars opined wright s work created new hybrid genre blending traditional traits heritage film youth oriented filmmaking techniques "


vec1 = np.array(d2v_film_model.infer_vector(string1.split()))
vec2 = d2v_film_model.infer_vector(string2.split())
vec3 = d2v_film_model.infer_vector(string3.split())
vec4 = d2v_film_model.infer_vector(string4.split())
vec5 = d2v_film_model.infer_vector(string5.split())
vec6 = d2v_film_model.infer_vector(string6.split())
vec7 = d2v_film_model.infer_vector(string7.split())

output = []
ordered_vectors = np.array([])
X = np.array([vec1, vec2, vec3, vec4, vec5, vec6, vec7])
db = DBSCAN(algorithm='auto', eps=0.49, leaf_size=30, metric='cosine', min_samples=1)
print(db.fit_predict(X))
clustered = db.fit_predict(X)
labels = db.labels_
n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)

clusters = [np.array(X[labels == i]) for i in range(n_clusters_)]
ordered_vectors = sorted(clusters, key = len, reverse = True)

for i in range(len(ordered_vectors)):
    output.append(np.mean(ordered_vectors[i], axis=0))
print(output)

unique_labels = set(labels)
colors = [plt.cm.Spectral(each)
          for each in np.linspace(0, 1, len(unique_labels))]
for k, col in zip(unique_labels, colors):
    class_member_mask = (labels == k)

    xy = X[class_member_mask]
    plt.plot(xy[:, 0], xy[:, 1], 'o', markerfacecolor=tuple(col),
             markeredgecolor='k', markersize=14)
    plt.title('Estimated number of clusters: %d' % n_clusters_)

plt.show()
